"""`ingestlib describe-schema NAME` — auto-document a SQL source's tables.

Schema-RAG and SQL generation both lean on plain-English table hints (the
`tables:` map in sources.yaml). On a clean schema you can write them by hand; on a
cryptic one (t_042, ss_sold_date_sk) you can't, and that is exactly where hints
matter most — auto-generated descriptions from sampled values have been shown to
beat even hand-written metadata (motherduck, LinkedIn). This command introspects
each table, samples a few rows, asks the LLM for a one-line description, and prints
a ready-to-paste `tables:` block. It never edits sources.yaml itself — you review
the descriptions and paste (or redirect with --out), because a wrong hint quietly
misleads generation.
"""
import asyncio

from pydantic import BaseModel, Field

from ingestlib.utils.logger import get_logger

logger = get_logger(__name__)

_CONCURRENCY = 8


class _TableDescription(BaseModel):
    """The model's one-line summary of a table."""
    description: str = Field(
        description="ONE concise sentence: what the table holds and what a row represents"
    )


async def _describe_all(source_name: str) -> dict[str, str]:
    from ingestlib.config import get_sources_config
    from ingestlib.foundations.llm import achat_structured
    from ingestlib.sources.sql.engine import reset_engines
    from ingestlib.sources.sql.schema import SchemaIndex

    spec = get_sources_config().sources.get(source_name)
    if spec is None:
        raise ValueError(f"unknown source {source_name!r} — declare it in sources.yaml")
    if spec.type in ("", "documents"):
        raise ValueError(f"source {source_name!r} is not a SQL database (type={spec.type!r})")

    reset_engines()
    try:
        index = SchemaIndex(spec.dsn, table_hints=spec.tables)
        await index.ensure_cards()                        # introspect + sample, no embedding
        tables = list(index._cards)
        sem = asyncio.Semaphore(_CONCURRENCY)

        async def describe(table: str) -> tuple[str, str | None]:
            async with sem:
                card = index._cards[table].render()
                try:
                    out = await achat_structured(
                        "Here is a database table's structure with a few example values. "
                        "Write ONE concise sentence describing what the table holds and what "
                        f"a single row represents. No prose beyond the sentence.\n\n{card}",
                        _TableDescription,
                    )
                    return table, out.description.strip()
                except Exception as exc:  # throttle/transient — skip this table, keep the rest
                    logger.warning("could not describe %r (skipped): %s", table, exc)
                    return table, None

        pairs = await asyncio.gather(*(describe(t) for t in tables))
        return {table: desc for table, desc in pairs if desc}
    finally:
        reset_engines()


def run_describe_schema(source_name: str, *, out: str | None = None) -> int:
    import os

    import yaml

    from ingestlib.utils.logger import configure

    if not os.environ.get("INGESTLIB_LOG_LEVEL"):
        configure(level="WARNING")

    descriptions = asyncio.run(_describe_all(source_name))
    if not descriptions:
        print(f"source {source_name!r} has no tables to describe")
        return 0

    block = (
        f"# generated by `ingestlib describe-schema {source_name}` — REVIEW before trusting;\n"
        f"# a wrong hint silently misleads generation. Paste under this source in sources.yaml.\n"
        + yaml.safe_dump({"tables": descriptions}, sort_keys=True, allow_unicode=True)
    )

    if out:
        with open(out, "w") as f:
            f.write(block)
        print(f"✓ wrote {len(descriptions)} table descriptions → {out} (review, then merge)")
    else:
        print(block, end="")
    return 0
